appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ORt8gFmlxUkyG7TXtWWQ15mKmsc43hLNdPG6BmGtBqikjFHiYfM0K41zDSyE3W137bW0mJdsjVm4rmADWKu8ZSox6sngooAy3Talk297FKhxkWSIGrsn+r0aaaKbpezzitWNlXFBFpkyLd1DrJ/SVTxqFGYln8ucI+zX/gofciCIxilcQBWLLdW1uZwi1MGqqCttrs0DAEXNZIpYwBDwvYPlgTJX5lERR5ZJ/Bu3a1DC6CDwfQUaM9T/4ovu3T3jlbppftrqXB8BzH6J/U1i/2+vwRetwusrZmGHTddFLcc059ZcjR00j3G1pAmmQ55PnfDaSrR5U1GqC2iNancldr7Wx+/vFdNZ3yIoaJTv3FlR5+kmLi34GHatlY117H40+tl1wZU/SMHs0XrUtulSIQC2YoMXBN9kVuKJUuW2b3J1wIOju8cXI1z5X7PHnjSoxxOniVtuBSyTs0/Yudt6NM9+kSBVo0+gSPAD9NzrjcsXFXNdX7lsC+QcTpGusWFuJXEWTMytaWoWdwXnZfVZG9WPSUHvc5mz8bBHRQuG4ghUYUfXfnJhNtXbIC7RZNegStog2eDdFCO6NpgDlmoen9i6cHjx3e6PoQc3HDyT1S8fWSozJ7ZYqxU3NcfKfw6lAUgzMwGXMzH9jny8cK/YNszfafFpiXcHMDvnkFhrVTQ=}
bot:
  automerge: true
